# Generated by Django 5.2.17 on 2026-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32)),
                ('account_key', models.CharField(max_length=64)),
                ('feed', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('data_through', models.DateField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'account_key', 'feed'), name='unique_social_connector')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32)),
                ('account_key', models.CharField(max_length=64)),
                ('subject_kind', models.CharField(default='account', max_length=16)),
                ('subject_id', models.CharField(max_length=128)),
                ('metric_key', models.CharField(max_length=64)),
                ('metric_label', models.CharField(max_length=80)),
                ('unit', models.CharField(max_length=16)),
                ('stat_date', models.DateField()),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=40)),
                ('value', models.PositiveBigIntegerField()),
                ('value_semantics', models.CharField(max_length=32)),
                ('source_provider', models.CharField(max_length=64)),
                ('source_reference', models.URLField(max_length=500)),
                ('fetched_at', models.DateTimeField()),
                ('run_id', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'metric_key', 'stat_date'], name='stats_obser_platfor_93c45d_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'account_key', 'subject_kind', 'subject_id', 'metric_key', 'stat_date', 'source_provider'), name='unique_social_observation')],
            },
        ),
    ]
