# Generated by Django 5.2.17 on 2026-09-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_kind', models.CharField(max_length=40)),
                ('period_end', models.DateField()),
                ('sent_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report_kind', 'period_end'), name='unique_social_report_delivery')],
            },
        ),
    ]
